language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3              # Same version as specified in build.gradle
    - android-28                      # SDK version
    - extra-android-m2repository      
    - extra-google-m2repository 
    - sys-img-armeabi-v7a-android-22  # Android Image
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
     
before_script:
    - wget http://services.gradle.org/distributions/gradle-4.4-bin.zip
    - unzip gradle-4.4-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.4
    - export PATH=$GRADLE_HOME/bin:$PATH
#    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#    - emulator -avd test -no-skin -no-audio -no-window &
#    - android-wait-for-emulator
#    - adb shell input keyevent 82 &
