language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.2              # Same version as specified in build.gradle
    - android-28                      # SDK version
    - extra-android-m2repository      # Additional Components
    - sys-img-armeabi-v7a-android-21  # Android Image

  licenses:
    - '.+'
     
# Run before running the build script
before_script:
    - wget http://services.gradle.org/distributions/gradle-4.4-bin.zip
    - unzip gradle-4.4-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.4
    - export PATH=$GRADLE_HOME/bin:$PATH
#    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#    - emulator -avd test -no-skin -no-audio -no-window &
#    - android-wait-for-emulator
#    - adb shell input keyevent 82 &
    
# Licenses to be accepted
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
#script:
#    - TERM=dumb ./gradlew test assembleDebug
